version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./tests/reports:/app/tests/reports
      - ./allure-results:/app/allure-results
    environment:
      - APP_URL=http://app:5000
    command: pytest

networks:
  default:
    name: hello-world-network